services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/certbot
    networks:
      - app-network
    depends_on:
      - app
      - certbot

  app:
    build: ./app
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - NGINX_HOST=localhost

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot --webroot-path=/var/www/certbot --noninteractive --agree-tos --email omaciasnarvaez@gmail.com -d python-app.myddns.me --cert-name python-app --keep-until-expiring; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

networks:
  app-network:
