apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        worker_connections  1024;  # Número máximo de conexiones que un worker puede manejar
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        resolver 127.0.0.11 valid=30s;

        upstream app {
            server python:8000;
        }

        server {
            listen 80;
            server_name localhost;

            location / {
                proxy_pass http://app;
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }
